### ISSUE TITLE
Combine dev servers into a single url for easy development

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#170]
To simplify development and not have to type the full URL like `http://192.168.0.64:3000/play?path=http://192.168.0.64:5000/default.json` on mobile devices, we could combine the dev servers into a single one.

I will look into building scenarios into the `web/static/dev-only` directory during development to allow them to be accessible from the same static server. This will allow us simplify the project config for development and remove some dependencies, making the project lighter to run in dev mode.

This should not affect how scenarios are built for production, as they should still be built into `content/dist` to be able to be deployed separately.

## TODO:

- [x] During development, build scenarios to `web/static/dev-only` instead of `content/dist`
- [x] Ensure `web/static/dev-only` is added to `.gitignore`
- [x] Ensure `web/static/dev-only` is removed before the built app gets built and published
- [x] Ensure production builds of scenarios are still built to `content/dist`
- [x] Remove unnecessary dependencies
- [x] Simplify dev scripts
- [x] Update README.md and `CONTRIBUTING.md` with new instructions.
- [x] Add `?dev=[SCENARIO_ID]` path parsing support to the game client, to automatically load development scenarios. Will greatly improve local development experience.

**Comment by Greenheart** [comment]
Resolved with https://github.com/Greenheart/swipeforfuture.com/commit/6e004424a36cd5a9a1cc6fe92d662f0c527b5754 and related previous commits! 🎉
